services:
  mqtt:
    image: eclipse-mosquitto:2
    configs:
      - source: mosquitto_conf
        target: /mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

  mesh_gateway:
    build: ./mesh_gateway
    environment:
      MQTT_HOST: mqtt
      CHANNEL_NAME: "${CHANNEL_NAME:-#public}"
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - mqtt
    restart: unless-stopped

  camp_router:
    build: ./camp_router
    environment:
      MQTT_HOST: mqtt
    depends_on:
      - mqtt
    restart: unless-stopped

  camp_terminal:
    build: ./camp_terminal
    environment:
      MQTT_HOST: mqtt
    ports:
      - "8080:8080"
    depends_on:
      - mqtt
    restart: unless-stopped

  camp_rally:
    build: ./camp_rally
    environment:
      MQTT_HOST: mqtt
    depends_on:
      - mqtt
    restart: unless-stopped

configs:
  mosquitto_conf:
    content: |
      listener 1883
      allow_anonymous true

